### ISSUE TITLE
Code optimization

### ISSUE THREAD

**Issue by CameronK** [CameronK/forcept#15]
FORCEPT needs to run on all devices without crippling lag. React modules must be optimized to increase speed.

# Todo:
- [ ] Reduce/eliminate usage of console.log
- [ ] Find a faster alternative to Object.keys
- [ ] Find other ways to optimize code
- [ ] Run benchmarks

**Comment by CameronK** [comment]
https://community.dynatrace.com/community/display/PUB/Best+Practices+on+JavaScript+and+AJAX+Performance

**Comment by CameronK** [comment]
http://archive.oreilly.com/pub/a/server-administration/excerpts/even-faster-websites/writing-efficient-javascript.html#the_switch_statement

**Comment by CameronK** [comment]
http://desalasworks.com/article/javascript-performance-techniques/
